"""Card database definitions for Duel Masters cards."""

from __future__ import annotations

from typing import Any, Dict, List

CARD_DATA: List[Dict[str, Any]] = [
    {
        "card_id": 100,
        "card_name": "蒼天の守護者ラ・ウラ・ギガ",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "ガーディアン",
        "cost": 1,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "◇ブロッカー \r\n■相手プレイヤーを攻撃できない。",
    },
    {
        "card_id": 200,
        "card_name": "雲霧の守護者ク・ラウド",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "ガーディアン",
        "cost": 2,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 300,
        "card_name": "鎮圧の使徒サリエス",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "イニシエート",
        "cost": 2,
        "power_disp": "3000",
        "mana": 1,
        "body_text": "◇ブロッカー \n■相手プレイヤーを攻撃できない。",
    },
    {
        "card_id": 400,
        "card_name": "晴天の守護者レゾ・パコス",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "ガーディアン",
        "cost": 3,
        "power_disp": "3000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 500,
        "card_name": "磁力の使徒マグリス",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "イニシエート",
        "cost": 4,
        "power_disp": "3000",
        "mana": 1,
        "body_text": "■バトルゾーンに出た時、カードを1枚引く。",
    },
    {
        "card_id": 600,
        "card_name": "琥珀草",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "スターライト・ツリー",
        "cost": 4,
        "power_disp": "3000",
        "mana": 1,
        "body_text": "◇S・トリガー",
    },
    {
        "card_id": 700,
        "card_name": "予言者コロン",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "ライトブリンガー",
        "cost": 4,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "◇S・トリガー \n■バトルゾーンに出た時、相手のクリーチャー1体をタップしてもよい。",
    },
    {
        "card_id": 800,
        "card_name": "浄化の精霊ウルス",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "エンジェル・コマンド",
        "cost": 6,
        "power_disp": "6000",
        "mana": 1,
        "body_text": "◇W・ブレイカー \n■自分のターン終了時、アンタップする。",
    },
    {
        "card_id": 900,
        "card_name": "光輪の精霊シャウナ",
        "card_type": "クリーチャー",
        "culture": "光",
        "race1": "エンジェル・コマンド",
        "cost": 7,
        "power_disp": "9500",
        "mana": 1,
        "body_text": "◇W・ブレイカー",
    },
    {
        "card_id": 1000,
        "card_name": "ソーラー・レイ",
        "card_type": "呪文",
        "culture": "光",
        "cost": 2,
        "mana": 1,
        "body_text": "◇S・トリガー \n■相手のクリーチャー1体をタップする。",
    },
    {
        "card_id": 1100,
        "card_name": "ムーンライト・フラッシュ",
        "card_type": "呪文",
        "culture": "光",
        "cost": 4,
        "mana": 1,
        "body_text": "■相手のクリーチャーを2体までタップする。",
    },
    {
        "card_id": 1200,
        "card_name": "守護聖天ラディア・バーレ",
        "card_type": "進化クリーチャー",
        "culture": "光",
        "race1": "ガーディアン",
        "cost": 6,
        "power_disp": "9500",
        "mana": 1,
        "body_text": "◇ブロッカー \n■進化－ガーディアン \n◇W・ブレイカー",
    },
    {
        "card_id": 1300,
        "card_name": "アクア・ガード",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "リキッド・ピープル",
        "cost": 1,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "◇ブロッカー \n■攻撃できない。",
    },
    {
        "card_id": 1400,
        "card_name": "アクア・ビークル",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "リキッド・ピープル",
        "cost": 2,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 1500,
        "card_name": "アクア・ハルカス",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "リキッド・ピープル",
        "cost": 3,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "■バトルゾーンに出た時、カードを1枚引く。",
    },
    {
        "card_id": 1600,
        "card_name": "キャンディ・ドロップ",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "サイバー・ウイルス",
        "cost": 3,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "■ブロックされない。",
    },
    {
        "card_id": 1700,
        "card_name": "ウォルタ",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "サイバーロード",
        "cost": 3,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "■攻撃する時、カードを1枚引く。",
    },
    {
        "card_id": 1800,
        "card_name": "ハンター・クラスター",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "サイバー・クラスター",
        "cost": 4,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "◇S・トリガー \n◇ブロッカー",
    },
    {
        "card_id": 1900,
        "card_name": "アクア・シューター",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "リキッド・ピープル",
        "cost": 4,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "◇ブロッカー",
    },
    {
        "card_id": 2000,
        "card_name": "アクア・ナイト",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "リキッド・ピープル",
        "cost": 5,
        "power_disp": "4000",
        "mana": 1,
        "body_text": "■破壊される時、かわりに手札に戻す。",
    },
    {
        "card_id": 2100,
        "card_name": "キング・オリオン",
        "card_type": "クリーチャー",
        "culture": "水",
        "race1": "リヴァイアサン",
        "cost": 7,
        "power_disp": "6000",
        "mana": 1,
        "body_text": "◇W・ブレイカー \n■ブロックされない。",
    },
    {
        "card_id": 2200,
        "card_name": "スパイラル・スライダー",
        "card_type": "呪文",
        "culture": "水",
        "cost": 2,
        "mana": 1,
        "body_text": "◇S・トリガー \n■相手のコスト6以下のクリーチャー1体を手札に戻す。",
    },
    {
        "card_id": 2300,
        "card_name": "ネオ・ブレイン",
        "card_type": "呪文",
        "culture": "水",
        "cost": 4,
        "mana": 1,
        "body_text": "◇S・トリガー \n■カードを2枚引く。",
    },
    {
        "card_id": 2400,
        "card_name": "クリスタル・ジャベリン",
        "card_type": "進化クリーチャー",
        "culture": "水",
        "race1": "リキッド・ピープル",
        "cost": 7,
        "power_disp": "7000",
        "mana": 1,
        "body_text": "■進化－リキッド・ピープル \n◇W・ブレイカー \n■破壊される時、かわりに手札に戻す。",
    },
    {
        "card_id": 2500,
        "card_name": "ブラッディ・イヤリング",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "ブレインジャッカー",
        "cost": 2,
        "power_disp": "4000",
        "mana": 1,
        "body_text": "◇ブロッカー \n■攻撃できない。 \n■バトルする時、バトルの後、このクリーチャーを破壊する。",
    },
    {
        "card_id": 2600,
        "card_name": "臓裂虫テンタイク・ワーム",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "パラサイトワーム",
        "cost": 2,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 2700,
        "card_name": "嘆きの影ベルベットフロー",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "ゴースト",
        "cost": 3,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "◇スレイヤー",
    },
    {
        "card_id": 2800,
        "card_name": "卵胞虫ゼリー・ワーム",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "パラサイトワーム",
        "cost": 3,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "■攻撃する時、相手の手札をランダムに1枚捨てさせる。",
    },
    {
        "card_id": 2900,
        "card_name": "暴食虫グレゴリア・ワーム",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "パラサイトワーム",
        "cost": 4,
        "power_disp": "3000",
        "mana": 1,
        "body_text": "◇S・トリガー",
    },
    {
        "card_id": 3000,
        "card_name": "汽車男",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "ヘドリアン",
        "cost": 4,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "◇S・トリガー\n■バトルゾーンに出た時、相手の手札をランダムに1枚捨てさせる。",
    },
    {
        "card_id": 3100,
        "card_name": "腐卵虫ハングワーム",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "パラサイトワーム",
        "cost": 5,
        "power_disp": "4000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 3200,
        "card_name": "暗黒の騎士ザガーン",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "デーモン・コマンド",
        "cost": 6,
        "power_disp": "7000",
        "mana": 1,
        "body_text": "◇W・ブレイカー",
    },
    {
        "card_id": 3300,
        "card_name": "混沌の獅子デスライガー",
        "card_type": "クリーチャー",
        "culture": "闇",
        "race1": "デーモン・コマンド",
        "cost": 7,
        "power_disp": "9000",
        "mana": 1,
        "body_text": "◇W・ブレイカー",
    },
    {
        "card_id": 3400,
        "card_name": "ファントム・バイツ",
        "card_type": "呪文",
        "culture": "闇",
        "cost": 3,
        "mana": 1,
        "body_text": "◇S・トリガー \n■このターン、相手のクリーチャー1体のパワーを-2000する。",
    },
    {
        "card_id": 3500,
        "card_name": "デス・スモーク",
        "card_type": "呪文",
        "culture": "闇",
        "cost": 4,
        "mana": 1,
        "body_text": "■相手のアンタップしているクリーチャー1体を破壊する。",
    },
    {
        "card_id": 3600,
        "card_name": "魔翼虫ジェノサイド・ワーム",
        "card_type": "進化クリーチャー",
        "culture": "闇",
        "race1": "パラサイトワーム",
        "cost": 6,
        "power_disp": "11000",
        "mana": 1,
        "body_text": "■進化－パラサイトワーム \n◇W・ブレイカー",
    },
    {
        "card_id": 3700,
        "card_name": "不死身男爵ボーグ",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "ヒューマノイド",
        "cost": 2,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 3800,
        "card_name": "喧嘩屋タイラー",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "ヒューマノイド",
        "cost": 2,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "■パワーアタッカー+2000",
    },
    {
        "card_id": 3900,
        "card_name": "クック・ポロン",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "ファイアー・バード",
        "cost": 2,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "■攻撃されない。",
    },
    {
        "card_id": 4000,
        "card_name": "双神兵カミカゼ",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "アーマロイド",
        "cost": 2,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "◇S・トリガー",
    },
    {
        "card_id": 4100,
        "card_name": "爆炎野郎ジョー",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "ヒューマノイド",
        "cost": 3,
        "power_disp": "3000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 4200,
        "card_name": "炎獣兵マグナム・ブルース",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "ドラゴノイド",
        "cost": 3,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "■自分の火のクリーチャーが他に1体でもあれば「パワーアタッカー+3000」を得る。",
    },
    {
        "card_id": 4300,
        "card_name": "掃討兵バーニング・ヘル",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "ドラゴノイド",
        "cost": 4,
        "power_disp": "3000",
        "mana": 1,
        "body_text": "■パワーアタッカー+2000",
    },
    {
        "card_id": 4400,
        "card_name": "撃墜団長メッツァー",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "ヒューマノイド",
        "cost": 4,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "■スピードアタッカー",
    },
    {
        "card_id": 4500,
        "card_name": "ボルシャック・ドラゴン",
        "card_type": "クリーチャー",
        "culture": "火",
        "race1": "アーマード・ドラゴン",
        "cost": 6,
        "power_disp": "6000",
        "mana": 1,
        "body_text": "◇W・ブレイカー \n■攻撃中、自分の墓地にある火のカード1枚につきパワーを+1000する。",
    },
    {
        "card_id": 4600,
        "card_name": "幻竜砲",
        "card_type": "呪文",
        "culture": "火",
        "cost": 3,
        "mana": 1,
        "body_text": "◇S・トリガー \n■相手のパワー2000以下のクリーチャー1体を破壊する。",
    },
    {
        "card_id": 4700,
        "card_name": "トルネード・フレーム",
        "card_type": "呪文",
        "culture": "火",
        "cost": 5,
        "mana": 1,
        "body_text": "◇S・トリガー \n■相手のパワー4000以下のクリーチャー1体を破壊する。",
    },
    {
        "card_id": 4800,
        "card_name": "機神装甲ヴァルディオス",
        "card_type": "進化クリーチャー",
        "culture": "火",
        "race1": "ヒューマノイド",
        "cost": 4,
        "power_disp": "6000",
        "mana": 1,
        "body_text": "■進化－ヒューマノイド \n◇W・ブレイカー \n■自分の他のヒューマノイドはすべてパワーを+1000する。",
    },
    {
        "card_id": 4900,
        "card_name": "炎のたてがみ",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ビーストフォーク",
        "cost": 2,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 5000,
        "card_name": "青銅の鎧",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ビーストフォーク",
        "cost": 3,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "■バトルゾーンに出た時、自分の山札の上から1枚目をマナゾーンに置く。",
    },
    {
        "card_id": 5100,
        "card_name": "銀の戦斧",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ビーストフォーク",
        "cost": 3,
        "power_disp": "1000",
        "mana": 1,
        "body_text": "■攻撃する時、自分の山札の上から1枚目をマナゾーンに置く。",
    },
    {
        "card_id": 5200,
        "card_name": "ソード・バタフライ",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ジャイアント・インセクト",
        "cost": 3,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "■パワーアタッカー+3000",
    },
    {
        "card_id": 5300,
        "card_name": "フォレスト・ホーネット",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ジャイアント・インセクト",
        "cost": 4,
        "power_disp": "4000",
        "mana": 1,
        "body_text": "",
    },
    {
        "card_id": 5400,
        "card_name": "デスブレード・ビートル",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ジャイアント・インセクト",
        "cost": 5,
        "power_disp": "3000",
        "mana": 1,
        "body_text": "■パワーアタッカー +4000 \n◇W・ブレイカー",
    },
    {
        "card_id": 5500,
        "card_name": "ウィップ・スコーピオン",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ジャイアント・インセクト",
        "cost": 5,
        "power_disp": "2000",
        "mana": 1,
        "body_text": "◇S・トリガー \n■パワーアタッカー+3000",
    },
    {
        "card_id": 5600,
        "card_name": "トゲ刺しマンドラ",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ツリーフォーク",
        "cost": 5,
        "power_disp": "4000",
        "mana": 1,
        "body_text": "■バトルゾーンに出た時、自分の墓地からクリーチャーを探索し、1枚をマナゾーンに置いてもよい。",
    },
    {
        "card_id": 5700,
        "card_name": "咆哮するグレート・ホーン",
        "card_type": "クリーチャー",
        "culture": "自然",
        "race1": "ホーン・ビースト",
        "cost": 7,
        "power_disp": "8000",
        "mana": 1,
        "body_text": "■パワーアタッカー+2000 \n◇W・ブレイカー",
    },
    {
        "card_id": 5800,
        "card_name": "フェアリー・ライフ",
        "card_type": "呪文",
        "culture": "自然",
        "cost": 2,
        "mana": 1,
        "body_text": "◇S・トリガー \n■自分の山札の上から1枚目をマナゾーンに置く。",
    },
    {
        "card_id": 5900,
        "card_name": "マドウ・スクラム",
        "card_type": "呪文",
        "culture": "自然",
        "cost": 4,
        "mana": 1,
        "body_text": "◇S・トリガー \n■相手のパワー5000以下のクリーチャー1体をマナゾーンに置く。",
    },
    {
        "card_id": 6000,
        "card_name": "大昆虫ガイアマンティス",
        "card_type": "進化クリーチャー",
        "culture": "自然",
        "race1": "ジャイアント・インセクト",
        "cost": 6,
        "power_disp": "9000",
        "mana": 1,
        "body_text": "■進化－ジャイアント・インセクト \n■パワー8000以下のクリーチャーにブロックされない。 \n◇W・ブレイカー",
    },
]

CARD_DATA_BY_ID: Dict[int, Dict[str, Any]] = {entry["card_id"]: entry for entry in CARD_DATA}
CARD_DATA_BY_NAME: Dict[str, Dict[str, Any]] = {
    entry["card_name"]: entry for entry in CARD_DATA
}

